
[dagger]
	#Disables all recipes for all Daggers.
	disable = false
	#Attack speed of Daggers.
	#Range: 0.0 ~ 4.0
	speed = 2.5
	#Base Damage of Daggers.
	#Range: 0.1 ~ 100.0
	base_damage = 2.5
	#Damage Multiplier for Daggers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5

[longsword]
	#Disables all recipes for all Longswords.
	disable = false
	#Attack speed of Longswords.
	#Range: 0.0 ~ 4.0
	speed = 1.399999976158142
	#Base Damage of Longswords.
	#Range: 0.1 ~ 100.0
	base_damage = 4.5
	#Damage Multiplier for Longswords.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.75

[katana]
	#Disables all recipes for all Katanas.
	disable = false
	#Attack speed of Katanas.
	#Range: 0.0 ~ 4.0
	speed = 2.0
	#Base Damage of Katanas.
	#Range: 0.1 ~ 100.0
	base_damage = 3.5
	#Damage Multiplier for Katanas.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0

[saber]
	#Disables all recipes for all Sabers.
	disable = false
	#Attack speed of Sabers.
	#Range: 0.0 ~ 4.0
	speed = 1.600000023841858
	#Base Damage of Sabers.
	#Range: 0.1 ~ 100.0
	base_damage = 3.5
	#Damage Multiplier for Sabers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.4

[rapier]
	#Disables all recipes for all Rapiers.
	disable = false
	#Attack speed of Rapiers.
	#Range: 0.0 ~ 4.0
	speed = 2.4000000953674316
	#Base Damage of Rapiers.
	#Range: 0.1 ~ 100.0
	base_damage = 2.0
	#Damage Multiplier for Rapiers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 0.8

[greatsword]
	#Disables all recipes for all Rapiers.
	disable = false
	#Attack speed of Rapiers.
	#Range: 0.0 ~ 4.0
	speed = 1.399999976158142
	#Base Damage of Rapiers.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0
	#Damage Multiplier for Rapiers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5

[club]
	#Disables all recipes for all Clubs.
	disable = false
	#Attack speed of Clubs.
	#Range: 0.0 ~ 4.0
	speed = 1.2999999523162842
	#Base Damage of Clubs.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0
	#Damage Multiplier for Clubs.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0

[cestus]
	#Disables all recipes for all Cestusae.
	disable = false
	#Attack speed of Cestusae.
	#Range: 0.0 ~ 4.0
	speed = 3.5
	#Base Damage of Cestusae.
	#Range: 0.1 ~ 100.0
	base_damage = 2.0
	#Damage Multiplier for Cestusae.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5

[battle_hammer]
	#Disables all recipes for all Battle Hammers.
	disable = false
	#Attack speed of Battle Hammers.
	#Range: 0.0 ~ 4.0
	speed = 0.800000011920929
	#Base Damage of Battle Hammers.
	#Range: 0.1 ~ 100.0
	base_damage = 5.0
	#Damage Multiplier for Battle Hammers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 2.0

[warhammer]
	#Disables all recipes for all Warhammers.
	disable = false
	#Attack speed of Warhammers.
	#Range: 0.0 ~ 4.0
	speed = 1.100000023841858
	#Base Damage of Warhammers.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0
	#Damage Multiplier for Warhammers.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5

[spear]
	#Disables all recipes for all Spears.
	disable = false
	#Attack speed of Spears.
	#Range: 0.0 ~ 4.0
	speed = 1.399999976158142
	#Base Damage of Spears.
	#Range: 0.1 ~ 100.0
	base_damage = 5.5
	#Damage Multiplier for Spears.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.4

[halberd]
	#Disables all recipes for all Halberds.
	disable = false
	#Attack speed of Halberds.
	#Range: 0.0 ~ 4.0
	speed = 1.2000000476837158
	#Base Damage of Halberds.
	#Range: 0.1 ~ 100.0
	base_damage = 5.0
	#Damage Multiplier for Halberds.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5

[pike]
	#Disables all recipes for all Pikes.
	disable = false
	#Attack speed of Pikes.
	#Range: 0.0 ~ 4.0
	speed = 1.399999976158142
	#Base Damage of Pikes.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0
	#Damage Multiplier for Pikes.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0

[lance]
	#Disables all recipes for all Lances.
	disable = false
	#Attack speed of Lances.
	#Range: 0.0 ~ 4.0
	speed = 1.0
	#Base Damage of Lances.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0
	#Damage Multiplier for Lances.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.75

[longbow]
	#Disables all recipes for all Longbows.
	disable = false

[heavy_crossbow]
	#Disables all recipes for all Heavy Crossbows.
	disable = false

[throwing_knife]
	#Disables all recipes for all Throwing Knives.
	disable = false
	#Attack speed of Throwing Knives.
	#Range: 0.0 ~ 4.0
	speed = 2.5
	#Base Damage of Throwing Knives.
	#Range: 0.1 ~ 100.0
	base_damage = 1.5
	#Damage Multiplier for Throwing Knives.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0

[tomahawk]
	#Disables all recipes for all Tomahawks.
	disable = false
	#Attack speed of Tomahawks.
	#Range: 0.0 ~ 4.0
	speed = 0.8999999761581421
	#Base Damage of Tomahawks.
	#Range: 0.1 ~ 100.0
	base_damage = 2.0
	#Damage Multiplier for Tomahawks.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.5

[javelin]
	#Disables all recipes for all Javelins.
	disable = false
	#Attack speed of Javelins.
	#Range: 0.0 ~ 4.0
	speed = 1.2000000476837158
	#Base Damage of Javelins.
	#Range: 0.1 ~ 100.0
	base_damage = 1.5
	#Damage Multiplier for Javelins.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.0

[boomerang]
	#Disables all recipes for all Boomerangs.
	disable = false
	#Attack speed of Boomerangs.
	#Range: 0.0 ~ 4.0
	speed = 2.0
	#Base Damage of Boomerangs.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0
	#Damage Multiplier for Boomerangs.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.4

[battleaxe]
	#Disables all recipes for all Battleaxes.
	disable = false
	#Attack speed of Battleaxes.
	#Range: 0.0 ~ 4.0
	speed = 1.0
	#Base Damage of Battleaxes.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0
	#Damage Multiplier for Battleaxes.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 2.05

[flanged_mace]
	#Disables all recipes for all Flanged Maces.
	disable = false
	#Attack speed of Flanged Maces.
	#Range: 0.0 ~ 4.0
	speed = 1.2000000476837158
	#Base Damage of Flanged Maces.
	#Range: 0.1 ~ 100.0
	base_damage = 3.0
	#Damage Multiplier for Flanged Maces.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.75

[glaive]
	#Disables all recipes for all Glaives.
	disable = false
	#Attack speed of Glaives.
	#Range: 0.0 ~ 4.0
	speed = 1.0
	#Base Damage of Glaives.
	#Range: 0.1 ~ 100.0
	base_damage = 4.0
	#Damage Multiplier for Glaives.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 1.75

[quarterstaff]
	#Disables all recipes for all Quarterstaves.
	disable = false
	#Attack speed of Quarterstaves.
	#Range: 0.0 ~ 4.0
	speed = 1.399999976158142
	#Base Damage of Quarterstaves.
	#Range: 0.1 ~ 100.0
	base_damage = 3.0
	#Damage Multiplier for Quarterstaves.
	#Range: 0.1 ~ 10.0
	damage_multiplier = 2.0

[copper]
	#Base Damage for copper weapons
	#Range: 0.1 ~ 100.0
	base_damage = 2.5
	#Durability for copper weapons
	#Range: 1 ~ 100000
	durability = 200
	#Set to true to disable copper weapons
	disable = false

[tin]
	#Base Damage for tin weapons
	#Range: 0.1 ~ 100.0
	base_damage = 2.75
	#Durability for tin weapons
	#Range: 1 ~ 100000
	durability = 180
	#Set to true to disable tin weapons
	disable = false

[bronze]
	#Base Damage for bronze weapons
	#Range: 0.1 ~ 100.0
	base_damage = 3.5
	#Durability for bronze weapons
	#Range: 1 ~ 100000
	durability = 320
	#Set to true to disable bronze weapons
	disable = false

[steel]
	#Base Damage for steel weapons
	#Range: 0.1 ~ 100.0
	base_damage = 4.75
	#Durability for steel weapons
	#Range: 1 ~ 100000
	durability = 520
	#Set to true to disable steel weapons
	disable = false

[silver]
	#Base Damage for silver weapons
	#Range: 0.1 ~ 100.0
	base_damage = 4.5
	#Durability for silver weapons
	#Range: 1 ~ 100000
	durability = 300
	#Set to true to disable silver weapons
	disable = false

[invar]
	#Base Damage for invar weapons
	#Range: 0.1 ~ 100.0
	base_damage = 4.8
	#Durability for invar weapons
	#Range: 1 ~ 100000
	durability = 350
	#Set to true to disable invar weapons
	disable = false

[platinum]
	#Base Damage for platinum weapons
	#Range: 0.1 ~ 100.0
	base_damage = 7.75
	#Durability for platinum weapons
	#Range: 1 ~ 100000
	durability = 1024
	#Set to true to disable platinum weapons
	disable = false

[electrum]
	#Base Damage for electrum weapons
	#Range: 0.1 ~ 100.0
	base_damage = 9.5
	#Durability for electrum weapons
	#Range: 1 ~ 100000
	durability = 750
	#Set to true to disable electrum weapons
	disable = false

[nickel]
	#Base Damage for nickel weapons
	#Range: 0.1 ~ 100.0
	base_damage = 2.8
	#Durability for nickel weapons
	#Range: 1 ~ 100000
	durability = 200
	#Set to true to disable nickel weapons
	disable = false

[lead]
	#Base Damage for lead weapons
	#Range: 0.1 ~ 100.0
	base_damage = 3.1
	#Durability for lead weapons
	#Range: 1 ~ 100000
	durability = 340
	#Set to true to disable lead weapons
	disable = false

[explosives]
	#Disables all recipes for explosive related items
	disable_recipe = false
	#Disables terrain damage for explosives in this mod such as Dynamite and Explosive Arrows. Is overridden by the 'mobGriefing' gamerule.
	disable_terrain_damage = false

[projectiles]
	#Disables Recipes for all new Arrows.
	disable_new_arrow_recipes = false
	#Disables Recipes for both Diamond Arrows and Diamond Bolts.
	disable_diamond_ammo_recipes = false
	#Disables all variants of the Arrow Quiver and the Bolt Quiver in this mod
	disable_quiver_recipes = false
	#Base damage for Wooden Arrows.
	#Range: 0.1 ~ 100.0
	base_damage_wood_arrow = 0.5
	#Base damage for Iron Arrows.
	#Range: 0.1 ~ 100.0
	base_damage_iron_arrow = 5.0
	#Base damage for Diamond Arrows.
	#Range: 0.1 ~ 100.0
	base_damage_diamond_arrow = 6.5
	#Base damage for Bolts.
	#Range: 0.1 ~ 100.0
	base_damage_bolt = 6.0
	#Base damage for Diamond Bolts.
	#Range: 0.1 ~ 100.0
	base_damage_diamond_bolt = 8.0
	#Bows in this blacklist will not get Arrows pulled out of the Arrow Quiver. Use the registry ID of the bow to add to this. e.g. "minecraft:bow"
	quiver_bow_blacklist = ["botania:crystal_bow"]

[loot]
	#Set to false to disable spawning Iron Weapons in Village Weaponsmith chests via loot table injection
	add_iron_weapons_to_village_blacksmith = false
	#Set to false to disable spawning Diamond Weapons in End City chests via loot table injection
	add_diamond_weapons_to_end_city = false
	#Chance for Zombies to spawn with Iron Melee Weapons on all difficulties apart from Hard and Hardcore
	#Range: 0.0 ~ 1.0
	zombie_with_melee_spawn_chance_normal = 0.3
	#Chance for Zombies to spawn with Iron Melee Weapons on Hard or Hardcore difficulty
	#Range: 0.0 ~ 1.0
	zombie_with_melee_spawn_chance_hard = 0.5
	#Set to true to disable spawning a Zombie with any weapons from this mod
	disable_spawning_zombie_with_weapon = false

[trading]
	#Set to true to disable Villagers (Weaponsmiths and Fletchers) from trading weapons from this mod
	disable = false

[traits]
	#Changes the "Chest Damage Bonus" Weapon Trait multiplier value
	#Range: 1.0 ~ 50.0
	damageBonusChestMultiplier = 1.5
	#Changes the "Riding Damage Bonus" Weapon Trait multiplier value
	#Range: 1.0 ~ 50.0
	damageBonusRidingMultiplier = 3.0
	#Changes the "Throwing Damage Bonus" Weapon Trait multiplier value
	#Range: 1.0 ~ 50.0
	damageBonusThrowMultiplier = 2.5
	#Changes the "Chest Damage Bonus" Weapon Trait multiplier value
	#Range: 1.0 ~ 50.0
	damageBonusThrowJavelinMultiplier = 3.0
	#Changes the "Chest Damage Bonus" Weapon Trait multiplier value
	#Range: 1.0 ~ 50.0
	damageBonusUnarmoredMultiplier = 2.5
	#Changes the "Chest Damage Bonus" Weapon Trait multiplier value
	#Range: 1.0 ~ 50.0
	damageBonusUndeadMultiplier = 1.5
	#Changes the percentage of damage absorbed by the "Damage Absorption" Weapon Trait
	#Range: 0.0 ~ 1.0
	damageAbsorptionFactor = 0.2
	#Changes the reach of any weapons with the "Reach I" Weapon Trait
	#Range: 5.0 ~ 15.0
	reach1Value = 6.0
	#Changes the reach of any weapons with the "Reach II" Weapon Trait
	#Range: 5.0 ~ 15.0
	reach2Value = 7.0
	#Changes the percentage of damage inflicted to enemies when sweep attacked on weapons with the "Sweep II" Weapon Trait
	#Range: 0.0 ~ 100.0
	sweep2Percentage = 50.0
	#Changes the percentage of damage inflicted to enemies when sweep attacked on weapons with the "Sweep III" Weapon Trait
	#Range: 0.0 ~ 100.0
	sweep3Percentage = 100.0
	#Changes the percentage of damage that ignores armor on weapons with the "Armor Piercing" Weapon Trait
	#Range: 0.0 ~ 100.0
	armorPiercePercentage = 50.0
	#Tweaks the hurt resistance ticks for weapons that use the "Quick Strike" Weapon Trait
	#Range: 10 ~ 20
	hurt_resistance_ticks = 10

[client]
	#Set to true to disable a new Crosshair for the Crossbow which visually shows inaccuracy, using the default Crosshair instead; false otherwise
	disable_new_crosshairs_crossbow = false
	#Set to true to disable a new Crosshair for Throwing Weapons which show the charge for them, using the default Crosshair instead; false otherwise
	disable_new_crosshairs_throwing_weapons = false
	#Set to force compatibility crosshairs for Crosshairs and Throwing Weapons. This won't work if the new crosshairs are disabled
	force_compatibility_crosshairs = false
	#Sets where the Quiver HUD Element should be aligned
	#Allowed Values: TOP_LEFT, TOP_CENTER, TOP_RIGHT, CENTER_LEFT, CENTER, CENTER_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
	quiver_hud_alignment = "BOTTOM_CENTER"
	#Sets where on the X-axis the Quiver HUD element should be off-set from it's alignment point
	#Range: -400 ~ 400
	quiver_hud_offset_x = -139
	#Sets where on the Y-axis the Quiver HUD element should be off-set from it's alignment point
	#Range: -400 ~ 400
	quiver_hud_offset_y = 63

